# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommendation.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'recommendation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14recommendation.proto\x12\x0erecommendation\"G\n\x07Request\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x0f\n\x07\x63ontext\x18\x02 \x03(\x03\x12\x0f\n\x07\x65xclude\x18\x03 \x03(\x03\x12\t\n\x01k\x18\x04 \x01(\x05\"<\n\x0cResponseItem\x12\x0f\n\x07item_id\x18\x01 \x01(\x03\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x0c\n\x04rank\x18\x03 \x01(\x05\"O\n\x08Response\x12+\n\x05items\x18\x01 \x03(\x0b\x32\x1c.recommendation.ResponseItem\x12\x16\n\x0ereturned_count\x18\x02 \x01(\x05\x32O\n\x0eRecommendation\x12=\n\x08Retrieve\x12\x17.recommendation.Request\x1a\x18.recommendation.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommendation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=40
  _globals['_REQUEST']._serialized_end=111
  _globals['_RESPONSEITEM']._serialized_start=113
  _globals['_RESPONSEITEM']._serialized_end=173
  _globals['_RESPONSE']._serialized_start=175
  _globals['_RESPONSE']._serialized_end=254
  _globals['_RECOMMENDATION']._serialized_start=256
  _globals['_RECOMMENDATION']._serialized_end=335
# @@protoc_insertion_point(module_scope)
